// Datos Oficiales POSFACE - UNAH
// Posgrado de la Facultad de Ciencias Económicas, Administrativas y Contables
// Fuente oficial: https://posface.unah.edu.hn/

const POSFASSE_DATA = {
  institucion: {
    nombre: "Universidad Nacional Autónoma de Honduras",
    sigla: "UNAH",
    facultad: "Facultad de Ciencias Económicas, Administrativas y Contables",
    unidad: "POSFACE - Posgrados de Ciencias Económicas",
    periodoActual: "II Período Académico 2026",
    portalOficial: "https://posface.unah.edu.hn/",
    coordinadorGeneral: "PhD. Joselyn Alvarado Siwady",
    cargoCoordinadorGeneral: "Coordinadora General POSFACE",
    edificio: "Edificio 1847, 5to piso / 5to nivel",
    campus: "Ciudad Universitaria, Tegucigalpa, M.D.C.",
    horarioAtencion: "Lunes a Viernes de 8:00am a 8:00pm",
    telefonoDirecto: "+504 2216-3000 / +504 2216-0000 Ext. 100840",
    whatsapp: "+504 8816-9962",
    instagram: "@posface_oficial",
    correoGeneral: "posface@unah.edu.hn",
    mision: "Somos una unidad académica que ofrece posgrados en el área de ciencias económicas a estudiantes universitarios que aspiran a una formación profesional superior, contribuyendo al desarrollo económico y productivo del país, otorgando a los estudiantes las herramientas intelectuales, a través de modelos educativos de vanguardia, acorde con los cambiantes retos exigidos por la globalización.",
    sobreNosotros: "Somos una unidad especializada dependiente de la Facultad de Ciencias Económicas, en donde se gestionan las maestrías y doctorados en las ramas de las Ciencias Económicas.",
    normativa: {
      notaAprobatoria: 75,
      reglamentoAprobacion: "Para aprobar una asignatura se requiere obtener una calificación NO menor de 75% (Art. 62 Reglamento Nivel Educación Superior, Art. 236 Normas Académicas UNAH, Art. 58 Reglamento General POSFACE).",
      registroDipp: "Las calificaciones finales son socializadas por su profesor y posteriormente registradas en el Sistema DIPP previa comprobación de solvencia de pago.",
      reprobacion: "El estudiante que repruebe sus asignaturas deberá gestionar su incorporación a otra promoción (o esperar la apertura de una nueva promoción).",
      plazoTesis: "Máximo de dos (2) años después de concluido el plan de estudios para concluir, presentar y aprobar trabajo de tesis o de graduación (Art. 251 Normas Académicas UNAH)."
    },
    lema: "Lucem Aspicio - Ciudad Universitaria, Tegucigalpa, M.D.C."
  },

  // Catálogo oficial de universidades de procedencia frecuentes
  universidadesProcedencia: [
    "UNAH - Universidad Nacional Autónoma de Honduras",
    "UNITEC - Universidad Tecnológica Centroamericana",
    "CEUTEC - Centro Universitario Tecnológico",
    "UTH - Universidad Tecnológica de Honduras",
    "UPNFM - Univ. Pedagógica Nacional Francisco Morazán",
    "UNICAH - Universidad Católica de Honduras",
    "USAP - Universidad de San Pedro Sula",
    "UJCV - Universidad José Cecilio del Valle",
    "UNAG - Univ. Nacional de Agricultura",
    "Universidad Extranjera / Internacional"
  ],

  // Oferta Académica Oficial POSFACE UNAH (Documento Oficial SOMOS POSFACE)
  // 1 Posdoctorado · 2 Doctorados · 7 Maestrías · 1 Centro BTC · 1 Diplomado Actuarial = 12 Programas
  maestrias: [
    // --- 1. MAESTRÍAS (7) ---
    {
      id: "M-MAE",
      codigo: "POS-MAE-01",
      tipo: "Maestría",
      nombre: "Maestría en Administración de Empresas",
      grado: "Maestría en Administración de Empresas (MAE)",
      modalidad: "Híbrida",
      duracionMeses: 24,
      totalUV: 54,
      coordinador: "MSc. Odette Bejarano",
      cargoCoordinador: "Coordinadora Académica",
      asistente: "Lcdo. Alejandro López (Asistente Académico)",
      correoCoordinacion: "posgrado.mae@unah.edu.hn",
      estado: "Activo",
      color: "#0284c7",
      descripcion: "Formación de alta dirección estratégica, finanzas corporativas, gestión del talento humano, toma de decisiones gerenciales y liderazgo competitivo global.",
      cohortesTotal: 4,
      estudiantesActivos: 42,
      asignaturasTotal: 14
    },
    {
      id: "M-MDNI",
      codigo: "POS-MDNI-02",
      tipo: "Maestría",
      nombre: "Maestría en Dirección de Negocios Internacionales",
      grado: "Maestría en Dirección de Negocios Internacionales",
      modalidad: "Virtual",
      duracionMeses: 20,
      totalUV: 48,
      coordinador: "MSc. Sunee Eiamwasant López",
      cargoCoordinador: "Coordinadora Académica",
      asistente: "Coordinación de Posgrados POSFACE",
      correoCoordinacion: "posgrado.negocios@unah.edu.hn",
      estado: "Activo",
      color: "#d97706",
      descripcion: "Especialización en comercio transfronterizo, tratados de libre comercio, logística internacional de suministros, finanzas multilaterales y negociación global.",
      cohortesTotal: 3,
      estudiantesActivos: 35,
      asignaturasTotal: 12
    },
    {
      id: "M-MDP",
      codigo: "POS-MDP-03",
      tipo: "Maestría",
      nombre: "Maestría en Dirección de Proyectos",
      grado: "Maestría en Dirección de Proyectos (Enfoque PMI / Ágil)",
      modalidad: "Híbrida",
      duracionMeses: 24,
      totalUV: 52,
      coordinador: "PhD. Fabiola Virginia Banegas",
      cargoCoordinador: "Coordinadora Académica",
      asistente: "Lcda. Yessica Martínez (Asistente Académica)",
      correoCoordinacion: "posgrado.proyectos@unah.edu.hn",
      estado: "Activo",
      color: "#059669",
      descripcion: "Gestión rigurosa de alcance, cronograma, riesgos, presupuesto, calidad y gobernanza estratégica en carteras y programas de proyectos públicos y privados.",
      cohortesTotal: 3,
      estudiantesActivos: 38,
      asignaturasTotal: 13
    },
    {
      id: "M-MGI",
      codigo: "POS-GI-04",
      tipo: "Maestría",
      nombre: "Maestría en Gestión Informática",
      grado: "Maestría en Gestión Informática",
      modalidad: "Virtual",
      duracionMeses: 24,
      totalUV: 52,
      coordinador: "MSc. Nelson Díaz",
      cargoCoordinador: "Coordinador Académico",
      asistente: "Lcda. Esther Durón (Asistente Académica)",
      correoCoordinacion: "posgrado.gestioninformatica@unah.edu.hn",
      estado: "Activo",
      color: "#7c3aed",
      descripcion: "Gobierno y alineación de tecnologías de información, ciberseguridad directiva, computación en la nube, arquitectura empresarial y analítica de datos.",
      cohortesTotal: 2,
      estudiantesActivos: 28,
      asignaturasTotal: 13
    },
    {
      id: "M-MME",
      codigo: "POS-MME-05",
      tipo: "Maestría",
      nombre: "Maestría en Mercadotecnia Estratégica y Gestión Comercial",
      grado: "Maestría en Mercadotecnia Estratégica y Gestión Comercial",
      modalidad: "Híbrida",
      duracionMeses: 20,
      totalUV: 48,
      coordinador: "MSc. Sunee Eiamwasant López",
      cargoCoordinador: "Coordinadora Académica",
      asistente: "Coordinación de Posgrados POSFACE",
      correoCoordinacion: "posgrado.mercadotecnia@unah.edu.hn",
      estado: "Activo",
      color: "#db2777",
      descripcion: "Diseño de estrategias comerciales omnicanal, comportamiento del consumidor digital, neuro-marketing, posicionamiento de marcas y analítica predictiva de mercado.",
      cohortesTotal: 2,
      estudiantesActivos: 26,
      asignaturasTotal: 12
    },
    {
      id: "M-MMIES",
      codigo: "POS-MIES-06",
      tipo: "Maestría",
      nombre: "Maestría en Metodologías de la Investigación Económica y Social",
      grado: "Maestría Académica en Metodologías de la Investigación",
      modalidad: "Presencial",
      duracionMeses: 24,
      totalUV: 56,
      coordinador: "PhD. Manuel Antonio Flores Fonseca",
      cargoCoordinador: "Coordinador Académico",
      asistente: "Coordinación General POSFACE",
      correoCoordinacion: "posgrado.metodologias@unah.edu.hn",
      estado: "Activo",
      color: "#ea580c",
      descripcion: "Formación científica de alto nivel en diseño metodológico cuantitativo y cualitativo, modelos econométricos aplicados y publicación de artículos en revistas indexadas.",
      cohortesTotal: 2,
      estudiantesActivos: 21,
      asignaturasTotal: 14
    },
    {
      id: "M-MCAF",
      codigo: "POS-CAF-07",
      tipo: "Maestría",
      nombre: "Maestría en Ciencias Actuariales y Financieras",
      grado: "Maestría en Ciencias Actuariales y Financieras",
      modalidad: "Presencial",
      duracionMeses: 24,
      totalUV: 54,
      coordinador: "MSc. Suyapa Margarita Martínez",
      cargoCoordinador: "Coordinadora Académica",
      asistente: "Lcda. Esther Durón (Asistente Académica)",
      correoCoordinacion: "posgrado.actuariales@unah.edu.hn",
      estado: "Activo",
      color: "#4f46e5",
      descripcion: "Modelado estocástico del riesgo, valoración matemática actuarial de fondos de pensiones, tablas biométricas, reservas de seguros y derivados financieros.",
      cohortesTotal: 1,
      estudiantesActivos: 18,
      asignaturasTotal: 14
    },

    // --- 2. DOCTORADOS (2) ---
    {
      id: "M-DCE",
      codigo: "POS-DCE-08",
      tipo: "Doctorado",
      nombre: "Doctorado en Ciencias Económicas",
      grado: "Doctorado (Ph.D.) en Ciencias Económicas",
      modalidad: "Presencial",
      duracionMeses: 36,
      totalUV: 72,
      coordinador: "PhD. Deysy Marlene Trejo Trejo",
      cargoCoordinador: "Coordinadora Académica",
      asistente: "Lcdo. Edgardo Matamoros (Asistente Académico)",
      correoCoordinacion: "doctorado.economicas@unah.edu.hn",
      estado: "Activo",
      color: "#0f766e",
      descripcion: "Investigación científica de frontera en macroeconomía, modelos estructurales, desarrollo económico y social, políticas públicas y econometría teórica.",
      cohortesTotal: 1,
      estudiantesActivos: 12,
      asignaturasTotal: 16
    },
    {
      id: "M-DDE",
      codigo: "POS-DDE-09",
      tipo: "Doctorado",
      nombre: "Doctorado en Dirección Empresarial",
      grado: "Doctorado (Ph.D.) en Dirección Empresarial",
      modalidad: "Presencial",
      duracionMeses: 36,
      totalUV: 72,
      coordinador: "PhD. Deysy Marlene Trejo Trejo",
      cargoCoordinador: "Coordinadora Académica",
      asistente: "Lcdo. Edgardo Matamoros (Asistente Académico)",
      correoCoordinacion: "doctorado.empresarial@unah.edu.hn",
      estado: "Activo",
      color: "#b45309",
      descripcion: "Máximo programa doctoral en teoría de la empresa, competitividad global, innovación corporativa, gobernanza empresarial y generación de conocimiento original.",
      cohortesTotal: 1,
      estudiantesActivos: 14,
      asignaturasTotal: 16
    },

    // --- 3. POSDOCTORADO (1) ---
    {
      id: "M-POSDOC",
      codigo: "POS-PDE-10",
      tipo: "Posdoctorado",
      nombre: "Posdoctorado en Desarrollo Económico, Innovación y Gestión Empresarial",
      grado: "Posdoctorado en Desarrollo Económico, Innovación y Gestión Empresarial",
      modalidad: "Híbrida",
      duracionMeses: 12,
      totalUV: 24,
      coordinador: "PhD. Joselyn Alvarado Siwady",
      cargoCoordinador: "Coordinadora General POSFACE",
      asistente: "Lcdo. Edgardo Matamoros (Asistente Académico)",
      correoCoordinacion: "posdoctorado.posface@unah.edu.hn",
      estado: "Activo",
      color: "#831843",
      descripcion: "Estudios posdoctorales avanzados orientados a investigadores doctorados para el desarrollo de líneas estratégicas de innovación, desarrollo económico y gestión.",
      cohortesTotal: 1,
      estudiantesActivos: 8,
      asignaturasTotal: 6
    },

    // --- 4. CENTRO DE FORMACIÓN EMPRESARIAL (1) ---
    {
      id: "M-BTC",
      codigo: "POS-BTC-11",
      tipo: "Centro Empresarial",
      nombre: "Centro de Formación Empresarial, Business Training Center (UNAH-BTC)",
      grado: "Centro de Formación Empresarial y Educación Ejecutiva",
      modalidad: "Híbrida",
      duracionMeses: 12,
      totalUV: 32,
      coordinador: "MSc. Marlon Galindo",
      cargoCoordinador: "Coordinador Académico UNAH-BTC",
      asistente: "Lcda. Helen Nuñez (Administradora) / Lcdo. Walter Morel (Marketing)",
      correoCoordinacion: "btc.posface@unah.edu.hn",
      estado: "Activo",
      color: "#ca8a04",
      descripcion: "Programas ejecutivos, educación continua gerencial, formación a la medida de empresas e instituciones y certificaciones prácticas de alto impacto.",
      cohortesTotal: 3,
      estudiantesActivos: 45,
      asignaturasTotal: 8
    },

    // --- 5. DIPLOMADO ACTUARIAL (1) ---
    {
      id: "M-DIP-ACT",
      codigo: "POS-DAC-12",
      tipo: "Diplomado",
      nombre: "Diplomado en Valuación Actuarial de Seguros y Riesgos Financieros",
      grado: "Diplomado en Valuación Actuarial de Seguros y Riesgos Financieros",
      modalidad: "Híbrida",
      duracionMeses: 6,
      totalUV: 16,
      coordinador: "MSc. Suyapa Margarita Martínez",
      cargoCoordinador: "Coordinadora Académica",
      asistente: "Lcda. Esther Durón (Asistente Académica)",
      correoCoordinacion: "diplomado.actuarial@unah.edu.hn",
      estado: "Activo",
      color: "#1e40af",
      descripcion: "Formación especializada en modelos actuariales de vida y no vida, cálculo de primas y reservas técnicas, solvencia y cuantificación de riesgos de mercado.",
      cohortesTotal: 2,
      estudiantesActivos: 22,
      asignaturasTotal: 5
    }
  ],

  // Cohortes activas POSFACE
  cohortes: [
    {
      id: "COH-MAE-2024",
      maestriaId: "M-MAE",
      nombre: "Cohorte MAE 2024-I",
      anio: 2024,
      fechaInicio: "2024-02-15",
      fechaFin: "2026-02-28",
      cupoLimite: 25,
      inscritos: 22,
      estado: "En Curso",
      etapa: "Ciclo IV - Finanzas Corporativas y Tesis",
      progresoPorcentaje: 75
    },
    {
      id: "COH-MAE-2025",
      maestriaId: "M-MAE",
      nombre: "Cohorte MAE 2025-I",
      anio: 2025,
      fechaInicio: "2025-02-10",
      fechaFin: "2027-02-28",
      cupoLimite: 25,
      inscritos: 20,
      estado: "En Curso",
      etapa: "Ciclo II - Dirección Estratégica",
      progresoPorcentaje: 35
    },
    {
      id: "COH-MDP-2024",
      maestriaId: "M-MDP",
      nombre: "Cohorte MDP 2024-II",
      anio: 2024,
      fechaInicio: "2024-06-01",
      fechaFin: "2026-06-30",
      cupoLimite: 25,
      inscritos: 21,
      estado: "En Curso",
      etapa: "Ciclo III - Gestión de Riesgos y Valor",
      progresoPorcentaje: 60
    },
    {
      id: "COH-MGI-2025",
      maestriaId: "M-MGI",
      nombre: "Cohorte MGI 2025-I",
      anio: 2025,
      fechaInicio: "2025-02-01",
      fechaFin: "2027-01-30",
      cupoLimite: 20,
      inscritos: 16,
      estado: "En Curso",
      etapa: "Ciclo I - Gobernanza y Ciberseguridad TI",
      progresoPorcentaje: 25
    },
    {
      id: "COH-MDNI-2024",
      maestriaId: "M-MDNI",
      nombre: "Cohorte MDNI 2024-I",
      anio: 2024,
      fechaInicio: "2024-03-01",
      fechaFin: "2025-12-15",
      cupoLimite: 25,
      inscritos: 18,
      estado: "En Curso",
      etapa: "Ciclo III - Logística Internacional",
      progresoPorcentaje: 65
    },
    {
      id: "COH-MME-2024",
      maestriaId: "M-MME",
      nombre: "Cohorte MME 2024-I",
      anio: 2024,
      fechaInicio: "2024-04-15",
      fechaFin: "2026-03-30",
      cupoLimite: 20,
      inscritos: 15,
      estado: "En Curso",
      etapa: "Ciclo III - Analítica y Neuromarketing",
      progresoPorcentaje: 55
    },
    {
      id: "COH-MMIES-2024",
      maestriaId: "M-MMIES",
      nombre: "Cohorte MMIES 2024-I",
      anio: 2024,
      fechaInicio: "2024-02-01",
      fechaFin: "2026-02-28",
      cupoLimite: 15,
      inscritos: 12,
      estado: "En Curso",
      etapa: "Ciclo IV - Seminario de Tesis Econométrica",
      progresoPorcentaje: 80
    },
    {
      id: "COH-MCAF-2025",
      maestriaId: "M-MCAF",
      nombre: "Cohorte MCAF 2025-I",
      anio: 2025,
      fechaInicio: "2025-02-15",
      fechaFin: "2027-02-28",
      cupoLimite: 15,
      inscritos: 11,
      estado: "En Curso",
      etapa: "Ciclo I - Teoría del Riesgo Financiero",
      progresoPorcentaje: 20
    }
  ],

  // Autoridades Académicas y Claustro Docente POSFACE (Documento SOMOS POSFACE)
  docentes: [
    {
      id: "AUT-01",
      dni: "0801-1974-05421",
      nombres: "Joselyn",
      apellidos: "Alvarado Siwady",
      grado: "Doctora (Ph.D.)",
      institucionGrado: "UNAH POSFACE",
      especialidad: "Coordinación General de Posgrados de Ciencias Económicas",
      correo: "posface@unah.edu.hn",
      telefono: "+504 2216-3000 Ext. 100840",
      estado: "Activo",
      categoria: "Coordinadora General POSFACE",
      tesistasAsignados: 6,
      materiasAsignadas: ["Seminario Posdoctoral", "Políticas de Desarrollo Económico"]
    },
    {
      id: "AUT-02",
      dni: "0801-1976-08912",
      nombres: "Odette",
      apellidos: "Bejarano",
      grado: "Máster (M.Sc.) en Dirección Empresarial",
      institucionGrado: "UNAH",
      especialidad: "Dirección Estratégica, Gestión de Empresas y Finanzas",
      correo: "posgrado.mae@unah.edu.hn",
      telefono: "+504 2216-3000 Ext. 100840",
      estado: "Activo",
      categoria: "Coordinadora Académica MAE",
      tesistasAsignados: 5,
      materiasAsignadas: ["Finanzas Corporativas Avanzadas", "Dirección Estratégica Gerencial"]
    },
    {
      id: "AUT-03",
      dni: "0801-1980-03415",
      nombres: "Sunee",
      apellidos: "Eiamwasant López",
      grado: "Máster (M.Sc.) en Mercadotecnia y Negocios",
      institucionGrado: "UNAH",
      especialidad: "Mercadotecnia Estratégica, Gestión Comercial y Negocios Internacionales",
      correo: "posgrado.mercadotecnia@unah.edu.hn",
      telefono: "+504 2216-3000 Ext. 100840",
      estado: "Activo",
      categoria: "Coordinadora Académica MME / MDNI",
      tesistasAsignados: 4,
      materiasAsignadas: ["Comercio y Negociación Internacional", "Estrategias de Mercadeo y Posicionamiento"]
    },
    {
      id: "AUT-04",
      dni: "0801-1978-01129",
      nombres: "Fabiola Virginia",
      apellidos: "Banegas",
      grado: "Doctora (Ph.D.) en Gestión de Proyectos",
      institucionGrado: "UNAH",
      especialidad: "Dirección, Evaluación y Formulación de Proyectos de Inversión",
      correo: "posgrado.proyectos@unah.edu.hn",
      telefono: "+504 2216-3000 Ext. 100840",
      estado: "Activo",
      categoria: "Coordinadora Académica MDP",
      tesistasAsignados: 4,
      materiasAsignadas: ["Gobernanza y Marco Ágil de Proyectos", "Gestión Integral de Riesgos"]
    },
    {
      id: "AUT-05",
      dni: "0801-1982-04533",
      nombres: "Nelson",
      apellidos: "Díaz",
      grado: "Máster (M.Sc.) en Tecnologías de la Información",
      institucionGrado: "UNAH",
      especialidad: "Gestión Informática, Ciberseguridad y Tecnologías Estratégicas",
      correo: "posgrado.gestioninformatica@unah.edu.hn",
      telefono: "+504 2216-3000 Ext. 100840",
      estado: "Activo",
      categoria: "Coordinador Académico MGI",
      tesistasAsignados: 3,
      materiasAsignadas: ["Gobierno de TI y Ciberseguridad Directiva", "Arquitectura Empresarial"]
    },
    {
      id: "AUT-06",
      dni: "0801-1970-07781",
      nombres: "Manuel Antonio",
      apellidos: "Flores Fonseca",
      grado: "Doctor (Ph.D.) en Métodos de Investigación",
      institucionGrado: "UNAH",
      especialidad: "Metodologías de la Investigación Económica y Social, Econometría",
      correo: "posgrado.metodologias@unah.edu.hn",
      telefono: "+504 2216-3000 Ext. 100840",
      estado: "Activo",
      categoria: "Coordinador Académico MMIES",
      tesistasAsignados: 5,
      materiasAsignadas: ["Métodos Cuantitativos y Econometría Aplicada", "Seminario de Tesis de Investigación"]
    },
    {
      id: "AUT-07",
      dni: "0801-1973-02290",
      nombres: "Suyapa Margarita",
      apellidos: "Martínez",
      grado: "Máster (M.Sc.) en Ciencias Actuariales",
      institucionGrado: "UNAH",
      especialidad: "Ciencias Actuariales, Modelación de Riesgos y Finanzas Cuantitativas",
      correo: "posgrado.actuariales@unah.edu.hn",
      telefono: "+504 2216-3000 Ext. 100840",
      estado: "Activo",
      categoria: "Coordinadora Académica MCAF / Diplomado",
      tesistasAsignados: 4,
      materiasAsignadas: ["Teoría del Riesgo Financiero y Actuarial", "Valuación Actuarial de Seguros"]
    },
    {
      id: "AUT-08",
      dni: "0801-1968-09144",
      nombres: "Deysy Marlene",
      apellidos: "Trejo Trejo",
      grado: "Doctora (Ph.D.) en Ciencias Económicas y Empresariales",
      institucionGrado: "UNAH",
      especialidad: "Dirección Empresarial, Macroeconomía y Modelos Estructurales",
      correo: "doctorado.posface@unah.edu.hn",
      telefono: "+504 2216-3000 Ext. 100840",
      estado: "Activo",
      categoria: "Coordinadora Académica DDE / DCE",
      tesistasAsignados: 6,
      materiasAsignadas: ["Teoría de la Firma y Competitividad", "Investigación Científica en Ciencias Económicas"]
    },
    {
      id: "AUT-09",
      dni: "0801-1981-06612",
      nombres: "Marlon",
      apellidos: "Galindo",
      grado: "Máster (M.Sc.) en Gestión Corporativa",
      institucionGrado: "UNAH",
      especialidad: "Capacitación Empresarial, Programas Ejecutivos y Competitividad",
      correo: "btc.posface@unah.edu.hn",
      telefono: "+504 2216-3000 Ext. 100840",
      estado: "Activo",
      categoria: "Coordinador Académico UNAH-BTC",
      tesistasAsignados: 2,
      materiasAsignadas: ["Gestión Ejecutiva y Desarrollo Organizacional"]
    }
  ],

  // Directorio del Equipo Administrativo Oficial POSFACE
  equipoAdministrativo: [
    { nombre: "MSc. Walther Acosta", cargo: "Administrador", unidad: "Posgrado de la Facultad de Ciencias Económicas POSFACE" },
    { nombre: "MSc. Yosmira Morales", cargo: "Administradora", unidad: "Posgrado de la Facultad de Ciencias Económicas POSFACE" },
    { nombre: "MSc. Claudia Gómez", cargo: "Administradora", unidad: "Posgrado de la Facultad de Ciencias Económicas POSFACE" },
    { nombre: "Lcda. Helen Nuñez", cargo: "Administradora", unidad: "Business Training Center UNAH-BTC" },
    { nombre: "Lcdo. Edgardo Matamoros", cargo: "Asistente Académico", unidad: "Programas de Doctorado y Posdoctorado" },
    { nombre: "Lcda. Esther Durón", cargo: "Asistente Académico", unidad: "Maestría en Ciencias Actuariales y Financieras / Gestión Informática" },
    { nombre: "Lcda. Yessica Martínez", cargo: "Asistente Académico", unidad: "Maestría en Dirección de Proyectos" },
    { nombre: "Lcdo. Alejandro López", cargo: "Asistente Académico", unidad: "Maestría en Administración de Empresas" },
    { nombre: "Lcdo. Elmer Díaz", cargo: "Asistente Académico", unidad: "Coordinación General POSFACE" },
    { nombre: "Lcda. Alejandra Henríquez", cargo: "Oficial de Registro", unidad: "Posgrado de la Facultad de Ciencias Económicas POSFACE" },
    { nombre: "Lcdo. Walter Morel", cargo: "Especialista en Marketing", unidad: "Business Training Center UNAH-BTC" },
    { nombre: "Leda Fiallos", cargo: "Asistente Operativo", unidad: "Posgrado de la Facultad de Ciencias Económicas POSFACE" },
    { nombre: "Cristian Díaz", cargo: "Auxiliar de Oficina", unidad: "Posgrado de la Facultad de Ciencias Económicas POSFACE" },
    { nombre: "Allan Puerto", cargo: "Auxiliar de Oficina", unidad: "Posgrado de la Facultad de Ciencias Económicas POSFACE" }
  ],

  // Directorio activo de expedientes POSFACE (vacío por defecto, solo inscripciones reales)
  estudiantes: [],

  // Malla curricular oficial de asignaturas
  asignaturas: [
    { codigo: "MAE-601", nombre: "Finanzas Corporativas Avanzadas", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MAE", docente: "MSc. José Roberto Argueta", modalidad: "Híbrida" },
    { codigo: "MAE-602", nombre: "Dirección Estratégica Gerencial", uv: 4, ciclo: "Ciclo II", maestriaId: "M-MAE", docente: "MSc. José Roberto Argueta", modalidad: "Híbrida" },
    { codigo: "MAE-603", nombre: "Gestión de Portafolios de Inversión", uv: 4, ciclo: "Ciclo III", maestriaId: "M-MAE", docente: "Dr. Nelson Rolando Ávila", modalidad: "Presencial" },
    { codigo: "MDNI-901", nombre: "Comercio y Negociación Internacional", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MDNI", docente: "Dra. Brenda Lizeth Flores", modalidad: "Virtual" },
    { codigo: "MDNI-902", nombre: "Logística y Transporte Multimodal", uv: 4, ciclo: "Ciclo II", maestriaId: "M-MDNI", docente: "Dra. Brenda Lizeth Flores", modalidad: "Virtual" },
    { codigo: "MDP-701", nombre: "Gobernanza y Marco Ágil de Proyectos", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MDP", docente: "Ing. Carlos Alberto Vindel", modalidad: "Híbrida" },
    { codigo: "MDP-702", nombre: "Gestión Integral de Riesgos en Proyectos", uv: 4, ciclo: "Ciclo II", maestriaId: "M-MDP", docente: "Ing. Carlos Alberto Vindel", modalidad: "Híbrida" },
    { codigo: "MGI-801", nombre: "Gobierno de TI y Ciberseguridad Directiva", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MGI", docente: "MSc. Marcio Francisco Valle", modalidad: "Virtual" },
    { codigo: "MGI-802", nombre: "Arquitectura Empresarial y Cloud Computing", uv: 4, ciclo: "Ciclo II", maestriaId: "M-MGI", docente: "MSc. Marcio Francisco Valle", modalidad: "Virtual" },
    { codigo: "MME-601", nombre: "Neuromarketing y Conducta Digital del Consumidor", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MME", docente: "MSc. Silvia Patricia Moncada", modalidad: "Híbrida" },
    { codigo: "MMIES-901", nombre: "Métodos Cuantitativos y Econometría Aplicada", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MMIES", docente: "Dr. Ramón Edgardo Cálix", modalidad: "Presencial" },
    { codigo: "MCAF-601", nombre: "Teoría del Riesgo Financiero y Actuarial", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MCAF", docente: "Dr. Nelson Rolando Ávila", modalidad: "Presencial" }
  ]
};

// Exportar globalmente para el frontend
if (typeof window !== 'undefined') {
  window.POSFASSE_DATA = POSFASSE_DATA;
}
