// Datos Oficiales POSFACE - UNAH
// Posgrado de la Facultad de Ciencias Económicas, Administrativas y Contables
// Fuente oficial: https://posface.unah.edu.hn/

const POSFASSE_DATA = {
  institucion: {
    nombre: "Universidad Nacional Autónoma de Honduras",
    sigla: "UNAH",
    facultad: "Facultad de Ciencias Económicas, Administrativas y Contables",
    unidad: "POSFACE - Posgrados de Ciencias Económicas",
    periodoActual: "II Período Académico 2026",
    portalOficial: "https://posface.unah.edu.hn/",
    coordinadorGeneral: "Dirección de Posgrados POSFACE",
    lema: "Lucem Aspicio - Ciudad Universitaria, Tegucigalpa, M.D.C."
  },

  // Catálogo oficial de universidades de procedencia frecuentes
  universidadesProcedencia: [
    "UNAH - Universidad Nacional Autónoma de Honduras",
    "UNITEC - Universidad Tecnológica Centroamericana",
    "CEUTEC - Centro Universitario Tecnológico",
    "UTH - Universidad Tecnológica de Honduras",
    "UPNFM - Univ. Pedagógica Nacional Francisco Morazán",
    "UNICAH - Universidad Católica de Honduras",
    "USAP - Universidad de San Pedro Sula",
    "UJCV - Universidad José Cecilio del Valle",
    "UNAG - Univ. Nacional de Agricultura",
    "Universidad Extranjera / Internacional"
  ],

  // Oferta Académica Oficial POSFACE UNAH (https://posface.unah.edu.hn/)
  maestrias: [
    {
      id: "M-MAE",
      codigo: "POS-MAE-01",
      nombre: "Maestría en Administración de Empresas",
      grado: "Maestría en Administración de Empresas (MAE)",
      modalidad: "Híbrida",
      duracionMeses: 24,
      totalUV: 54,
      coordinador: "MSc. José Roberto Argueta",
      correoCoordinacion: "posgrado.mae@unah.edu.hn",
      estado: "Activo",
      color: "#0284c7",
      descripcion: "Formación de alta dirección estratégica, finanzas corporativas, gestión del talento y liderazgo gerencial en entornos globales competitivos.",
      cohortesTotal: 4,
      estudiantesActivos: 42,
      asignaturasTotal: 14
    },
    {
      id: "M-MDNI",
      codigo: "POS-DNI-02",
      nombre: "Maestría en Dirección de Negocios Internacionales",
      grado: "Maestría en Dirección de Negocios Internacionales",
      modalidad: "Virtual",
      duracionMeses: 20,
      totalUV: 48,
      coordinador: "Dra. Brenda Lizeth Flores",
      correoCoordinacion: "posgrado.negocios@unah.edu.hn",
      estado: "Activo",
      color: "#d97706",
      descripcion: "Especialización en comercio exterior, logística transfronteriza, tratados de libre comercio, finanzas globales y negociación multilateral.",
      cohortesTotal: 3,
      estudiantesActivos: 35,
      asignaturasTotal: 12
    },
    {
      id: "M-MDP",
      codigo: "POS-DP-03",
      nombre: "Maestría en Dirección de Proyectos",
      grado: "Maestría en Dirección de Proyectos (Enfoque PMI / Ágil)",
      modalidad: "Híbrida",
      duracionMeses: 24,
      totalUV: 52,
      coordinador: "Ing. Carlos Alberto Vindel (PMP)",
      correoCoordinacion: "posgrado.proyectos@unah.edu.hn",
      estado: "Activo",
      color: "#059669",
      descripcion: "Gestión rigurosa de alcance, cronograma, riesgos, presupuesto y gobernanza estratégica en carteras de proyectos públicos y privados.",
      cohortesTotal: 3,
      estudiantesActivos: 38,
      asignaturasTotal: 13
    },
    {
      id: "M-MGI",
      codigo: "POS-GI-04",
      nombre: "Maestría en Gestión Informática",
      grado: "Maestría en Gestión Informática y Tecnologías Estratégicas",
      modalidad: "Virtual",
      duracionMeses: 24,
      totalUV: 52,
      coordinador: "MSc. Marcio Francisco Valle",
      correoCoordinacion: "posgrado.gestioninformatica@unah.edu.hn",
      estado: "Activo",
      color: "#7c3aed",
      descripcion: "Gobierno de TI, ciberseguridad directiva, arquitectura de sistemas empresariales, computación en la nube y analítica avanzada para negocios.",
      cohortesTotal: 2,
      estudiantesActivos: 28,
      asignaturasTotal: 13
    },
    {
      id: "M-MME",
      codigo: "POS-ME-05",
      nombre: "Maestría en Mercadotecnia Estratégica",
      grado: "Maestría en Mercadotecnia Estratégica",
      modalidad: "Híbrida",
      duracionMeses: 20,
      totalUV: 48,
      coordinador: "MSc. Silvia Patricia Moncada",
      correoCoordinacion: "posgrado.mercadotecnia@unah.edu.hn",
      estado: "Activo",
      color: "#db2777",
      descripcion: "Diseño omnicanal, comportamiento del consumidor digital, neuro-marketing, posicionamiento de marcas y analítica predictiva de mercados.",
      cohortesTotal: 2,
      estudiantesActivos: 26,
      asignaturasTotal: 12
    },
    {
      id: "M-MMIES",
      codigo: "POS-MIES-06",
      nombre: "Maestría en Metodologías de la Investigación Económica y Social",
      grado: "Maestría Académica de Investigación",
      modalidad: "Presencial",
      duracionMeses: 24,
      totalUV: 56,
      coordinador: "Dr. Ramón Edgardo Cálix",
      correoCoordinacion: "posgrado.metodologias@unah.edu.hn",
      estado: "Activo",
      color: "#ea580c",
      descripcion: "Diseño metodológico avanzado, econometría aplicada, métodos mixtos y preparación de investigaciones de impacto indexadas.",
      cohortesTotal: 2,
      estudiantesActivos: 21,
      asignaturasTotal: 14
    },
    {
      id: "M-MCAF",
      codigo: "POS-CAF-07",
      nombre: "Maestría en Ciencias Actuariales y Financieras",
      grado: "Maestría en Ciencias Actuariales y Financieras",
      modalidad: "Presencial",
      duracionMeses: 24,
      totalUV: 54,
      coordinador: "Dr. Nelson Rolando Ávila",
      correoCoordinacion: "posgrado.actuariales@unah.edu.hn",
      estado: "Activo",
      color: "#4f46e5",
      descripcion: "Modelado estocástico del riesgo, valoración matemática y actuarial de sistemas de pensiones, seguros y derivados financieros.",
      cohortesTotal: 1,
      estudiantesActivos: 18,
      asignaturasTotal: 14
    },
    {
      id: "M-DDE",
      codigo: "POS-DDE-08",
      nombre: "Doctorado en Dirección Empresarial",
      grado: "Doctorado (Ph.D.) en Dirección Empresarial",
      modalidad: "Presencial",
      duracionMeses: 36,
      totalUV: 72,
      coordinador: "Dr. José Efraín Deras",
      correoCoordinacion: "doctorado.empresarial@unah.edu.hn",
      estado: "Activo",
      color: "#b45309",
      descripcion: "Máximo programa doctoral en teoría de la firma, competitividad internacional, innovación corporativa y tesis doctorales de rigor global.",
      cohortesTotal: 1,
      estudiantesActivos: 14,
      asignaturasTotal: 16
    },
    {
      id: "M-DCE",
      codigo: "POS-DCE-09",
      nombre: "Doctorado en Ciencias Económicas",
      grado: "Doctorado (Ph.D.) en Ciencias Económicas",
      modalidad: "Presencial",
      duracionMeses: 36,
      totalUV: 72,
      coordinador: "Dra. Mirna Suyapa Zepeda",
      correoCoordinacion: "doctorado.economicas@unah.edu.hn",
      estado: "Activo",
      color: "#0f766e",
      descripcion: "Investigación científica de vanguardia en macroeconomía, modelos estructurales, desarrollo económico y economía monetaria.",
      cohortesTotal: 1,
      estudiantesActivos: 12,
      asignaturasTotal: 16
    },
    {
      id: "M-BTC",
      codigo: "POS-BTC-10",
      nombre: "UNAH Business Training Center (UNAH-BTC)",
      grado: "Centro de Educación Ejecutiva y Formación Empresarial",
      modalidad: "Híbrida",
      duracionMeses: 12,
      totalUV: 32,
      coordinador: "Lic. Karla Iveth Romero",
      correoCoordinacion: "btc.posface@unah.edu.hn",
      estado: "Activo",
      color: "#eab308",
      descripcion: "Programas ejecutivos, diplomados de alta especialización empresarial y certificaciones directivas a la medida de la industria.",
      cohortesTotal: 3,
      estudiantesActivos: 45,
      asignaturasTotal: 8
    }
  ],

  // Cohortes activas POSFACE
  cohortes: [
    {
      id: "COH-MAE-2024",
      maestriaId: "M-MAE",
      nombre: "Cohorte MAE 2024-I",
      anio: 2024,
      fechaInicio: "2024-02-15",
      fechaFin: "2026-02-28",
      cupoLimite: 25,
      matriculados: 22,
      estado: "En Curso",
      etapa: "Ciclo IV - Finanzas Corporativas y Tesis",
      progresoPorcentaje: 75
    },
    {
      id: "COH-MAE-2025",
      maestriaId: "M-MAE",
      nombre: "Cohorte MAE 2025-I",
      anio: 2025,
      fechaInicio: "2025-02-10",
      fechaFin: "2027-02-28",
      cupoLimite: 25,
      matriculados: 20,
      estado: "En Curso",
      etapa: "Ciclo II - Dirección Estratégica",
      progresoPorcentaje: 35
    },
    {
      id: "COH-MDP-2024",
      maestriaId: "M-MDP",
      nombre: "Cohorte MDP 2024-II",
      anio: 2024,
      fechaInicio: "2024-06-01",
      fechaFin: "2026-06-30",
      cupoLimite: 25,
      matriculados: 21,
      estado: "En Curso",
      etapa: "Ciclo III - Gestión de Riesgos y Valor",
      progresoPorcentaje: 60
    },
    {
      id: "COH-MGI-2025",
      maestriaId: "M-MGI",
      nombre: "Cohorte MGI 2025-I",
      anio: 2025,
      fechaInicio: "2025-02-01",
      fechaFin: "2027-01-30",
      cupoLimite: 20,
      matriculados: 16,
      estado: "En Curso",
      etapa: "Ciclo I - Gobernanza y Ciberseguridad TI",
      progresoPorcentaje: 25
    },
    {
      id: "COH-MDNI-2024",
      maestriaId: "M-MDNI",
      nombre: "Cohorte MDNI 2024-I",
      anio: 2024,
      fechaInicio: "2024-03-01",
      fechaFin: "2025-12-15",
      cupoLimite: 25,
      matriculados: 18,
      estado: "En Curso",
      etapa: "Ciclo III - Logística Internacional",
      progresoPorcentaje: 65
    },
    {
      id: "COH-MME-2024",
      maestriaId: "M-MME",
      nombre: "Cohorte MME 2024-I",
      anio: 2024,
      fechaInicio: "2024-04-15",
      fechaFin: "2026-03-30",
      cupoLimite: 20,
      matriculados: 15,
      estado: "En Curso",
      etapa: "Ciclo III - Analítica y Neuromarketing",
      progresoPorcentaje: 55
    },
    {
      id: "COH-MMIES-2024",
      maestriaId: "M-MMIES",
      nombre: "Cohorte MMIES 2024-I",
      anio: 2024,
      fechaInicio: "2024-02-01",
      fechaFin: "2026-02-28",
      cupoLimite: 15,
      matriculados: 12,
      estado: "En Curso",
      etapa: "Ciclo IV - Seminario de Tesis Econométrica",
      progresoPorcentaje: 80
    },
    {
      id: "COH-MCAF-2025",
      maestriaId: "M-MCAF",
      nombre: "Cohorte MCAF 2025-I",
      anio: 2025,
      fechaInicio: "2025-02-15",
      fechaFin: "2027-02-28",
      cupoLimite: 15,
      matriculados: 11,
      estado: "En Curso",
      etapa: "Ciclo I - Teoría del Riesgo Financiero",
      progresoPorcentaje: 20
    }
  ],

  // Directorio del Claustro Docente POSFACE
  docentes: [
    {
      id: "DOC-01",
      dni: "0801-1970-01289",
      nombres: "José Roberto",
      apellidos: "Argueta Castillo",
      grado: "Doctor (Ph.D.) en Ciencias Empresariales",
      institucionGrado: "Universidad de Valencia (España)",
      especialidad: "Finanzas Corporativas y Dirección Estratégica",
      correo: "jose.argueta@unah.edu.hn",
      telefono: "+504 9845-1230",
      estado: "Activo",
      categoria: "Profesor Titular V",
      tesistasAsignados: 5,
      materiasAsignadas: ["Finanzas Corporativas Avanzadas", "Dirección Estratégica Gerencial"]
    },
    {
      id: "DOC-02",
      dni: "0801-1975-04512",
      nombres: "Brenda Lizeth",
      apellidos: "Flores Meza",
      grado: "Doctora (Ph.D.) en Comercio Internacional",
      institucionGrado: "Universidad de Barcelona",
      especialidad: "Tratados Comerciales y Cadena de Suministro Global",
      correo: "brenda.flores@unah.edu.hn",
      telefono: "+504 9912-8840",
      estado: "Activo",
      categoria: "Profesora Titular IV",
      tesistasAsignados: 4,
      materiasAsignadas: ["Comercio y Negociación Internacional", "Logística Global"]
    },
    {
      id: "DOC-03",
      dni: "0801-1980-00892",
      nombres: "Carlos Alberto",
      apellidos: "Vindel Lagos",
      grado: "Máster (M.Sc.) en Gestión de Proyectos, PMP®",
      institucionGrado: "Penn State University (EE.UU.)",
      especialidad: "Metodologías Ágiles, Portafolios de Inversión y PMI",
      correo: "carlos.vindel@unah.edu.hn",
      telefono: "+504 9760-4411",
      estado: "Activo",
      categoria: "Profesor Titular III",
      tesistasAsignados: 4,
      materiasAsignadas: ["Gobernanza y Marco Ágil de Proyectos", "Gestión de Riesgos"]
    },
    {
      id: "DOC-04",
      dni: "0801-1982-03319",
      nombres: "Marcio Francisco",
      apellidos: "Valle Zelaya",
      grado: "Doctor en Informática de Gestión",
      institucionGrado: "Tecnológico de Monterrey (ITESM)",
      especialidad: "Gobierno de TI, Ciberseguridad y Big Data",
      correo: "marcio.valle@unah.edu.hn",
      telefono: "+504 9552-3390",
      estado: "Activo",
      categoria: "Profesor Auxiliar IV",
      tesistasAsignados: 3,
      materiasAsignadas: ["Gobierno de TI y Ciberseguridad", "Arquitectura Empresarial"]
    },
    {
      id: "DOC-05",
      dni: "0801-1978-02451",
      nombres: "Ramón Edgardo",
      apellidos: "Cálix Moncada",
      grado: "Doctor (Ph.D.) en Métodos Cuantitativos",
      institucionGrado: "UNAM (México)",
      especialidad: "Econometría Estructural y Series Temporales",
      correo: "ramon.calix@unah.edu.hn",
      telefono: "+504 9641-7715",
      estado: "Activo",
      categoria: "Profesor Titular V",
      tesistasAsignados: 3,
      materiasAsignadas: ["Econometría Avanzada", "Seminario de Tesis Cuantitativa"]
    }
  ],

  // Expedientes Estudiantiles POSFACE (con Universidad de Procedencia e Índice de Pregrado)
  estudiantes: [
    {
      id: "EST-01",
      cuentaUNAH: "20181003491",
      dni: "0801-1996-05423",
      nombres: "Andrea Nicole",
      apellidos: "Pineda Castro",
      correoInstitucional: "andrea.pineda@unah.edu.hn",
      telefono: "+504 9874-3210",
      universidadProcedencia: "UNAH - Universidad Nacional Autónoma de Honduras",
      tituloValidadoUNAH: "Exento",
      indicePregrado: 88.5,
      carreraPregrado: "Licenciatura en Administración de Empresas",
      maestriaId: "M-MAE",
      cohorteId: "COH-MAE-2024",
      estado: "Activo",
      fechaIngreso: "15/02/2024",
      promedio: 92.4,
      uvsAprobadas: 42,
      totalUVs: 54,
      tituloTesis: "Modelo de optimización financiera para microfinanzas pospandemia en Tegucigalpa",
      tutorTesis: "MSc. José Roberto Argueta",
      calificacionesRecientes: [
        { asignatura: "Finanzas Corporativas Avanzadas", codigo: "MAE-601", nota: 94, estado: "Aprobada" },
        { asignatura: "Dirección Estratégica Gerencial", codigo: "MAE-602", nota: 91, estado: "Aprobada" },
        { asignatura: "Gestión de Portafolios de Inversión", codigo: "MAE-603", nota: 92, estado: "Aprobada" }
      ]
    },
    {
      id: "EST-02",
      cuentaUNAH: "20192004512",
      dni: "0501-1995-12098",
      nombres: "Jorge Alberto",
      apellidos: "Mendoza Velásquez",
      correoInstitucional: "jorge.mendoza@unah.edu.hn",
      telefono: "+504 9540-1122",
      universidadProcedencia: "UNITEC - Universidad Tecnológica Centroamericana",
      tituloValidadoUNAH: "Si",
      indicePregrado: 86.2,
      carreraPregrado: "Ingeniería Industrial y de Sistemas",
      maestriaId: "M-MDP",
      cohorteId: "COH-MDP-2024",
      estado: "Activo",
      fechaIngreso: "01/06/2024",
      promedio: 89.1,
      uvsAprobadas: 32,
      totalUVs: 52,
      tituloTesis: "Implementación de marcos ágiles Scrum en proyectos de infraestructura pública",
      tutorTesis: "Ing. Carlos Alberto Vindel",
      calificacionesRecientes: [
        { asignatura: "Gobernanza y Marco Ágil de Proyectos", codigo: "MDP-701", nota: 88, estado: "Aprobada" },
        { asignatura: "Gestión Integral de Riesgos", codigo: "MDP-702", nota: 90, estado: "Aprobada" }
      ]
    },
    {
      id: "EST-03",
      cuentaUNAH: "20161008741",
      dni: "0801-1994-03219",
      nombres: "Karla Melissa",
      apellidos: "Avila Zepeda",
      correoInstitucional: "karla.avila@unah.edu.hn",
      telefono: "+504 9980-6644",
      universidadProcedencia: "UNAH - Universidad Nacional Autónoma de Honduras",
      tituloValidadoUNAH: "Exento",
      indicePregrado: 94.0,
      carreraPregrado: "Licenciatura en Informática Administrativa",
      maestriaId: "M-MGI",
      cohorteId: "COH-MGI-2025",
      estado: "Activo",
      fechaIngreso: "01/02/2025",
      promedio: 95.8,
      uvsAprobadas: 16,
      totalUVs: 52,
      tituloTesis: "Modelo de gobernanza de ciberseguridad basado en NIST para instituciones financieras",
      tutorTesis: "MSc. Marcio Francisco Valle",
      calificacionesRecientes: [
        { asignatura: "Gobierno de TI y Ciberseguridad", codigo: "MGI-801", nota: 96, estado: "Aprobada" },
        { asignatura: "Arquitectura Empresarial en la Nube", codigo: "MGI-802", nota: 95, estado: "Aprobada" }
      ]
    },
    {
      id: "EST-04",
      cuentaUNAH: "20201001205",
      dni: "0801-1997-09941",
      nombres: "Luis Fernando",
      apellidos: "Gómez Barrientos",
      correoInstitucional: "luis.gomez@unah.edu.hn",
      telefono: "+504 9631-5580",
      universidadProcedencia: "CEUTEC - Centro Universitario Tecnológico",
      tituloValidadoUNAH: "Si",
      indicePregrado: 83.4,
      carreraPregrado: "Licenciatura en Comercio Internacional",
      maestriaId: "M-MDNI",
      cohorteId: "COH-MDNI-2024",
      estado: "Activo",
      fechaIngreso: "01/03/2024",
      promedio: 87.6,
      uvsAprobadas: 30,
      totalUVs: 48,
      tituloTesis: "Estrategias de internacionalización para cooperativas de café especial hacia el mercado asiático",
      tutorTesis: "Dra. Brenda Lizeth Flores",
      calificacionesRecientes: [
        { asignatura: "Comercio y Negociación Internacional", codigo: "MDNI-901", nota: 87, estado: "Aprobada" },
        { asignatura: "Logística y Transporte Multimodal", codigo: "MDNI-902", nota: 88, estado: "Aprobada" }
      ]
    },
    {
      id: "EST-05",
      cuentaUNAH: "20172030114",
      dni: "0301-1993-01124",
      nombres: "Claudia María",
      apellidos: "Reyes Portillo",
      correoInstitucional: "claudia.reyes@unah.edu.hn",
      telefono: "+504 9471-2299",
      universidadProcedencia: "UNAH - Universidad Nacional Autónoma de Honduras",
      tituloValidadoUNAH: "Exento",
      indicePregrado: 90.5,
      carreraPregrado: "Licenciatura en Mercadotecnia",
      maestriaId: "M-MME",
      cohorteId: "COH-MME-2024",
      estado: "En Tesis",
      fechaIngreso: "15/04/2024",
      promedio: 93.2,
      uvsAprobadas: 40,
      totalUVs: 48,
      tituloTesis: "Impacto del neuromarketing digital en decisiones de compra en el e-commerce hondureño",
      tutorTesis: "MSc. Silvia Patricia Moncada",
      calificacionesRecientes: [
        { asignatura: "Neuromarketing y Conducta Digital", codigo: "MME-601", nota: 95, estado: "Aprobada" },
        { asignatura: "Analítica Predictiva de Mercados", codigo: "MME-602", nota: 92, estado: "Aprobada" }
      ]
    },
    {
      id: "EST-06",
      cuentaUNAH: "20151000958",
      dni: "0801-1992-07612",
      nombres: "Héctor Rolando",
      apellidos: "Mejía Solórzano",
      correoInstitucional: "hector.mejia@unah.edu.hn",
      telefono: "+504 9811-0033",
      universidadProcedencia: "UTH - Universidad Tecnológica de Honduras",
      tituloValidadoUNAH: "Si",
      indicePregrado: 81.8,
      carreraPregrado: "Licenciatura en Gerencia de Negocios",
      maestriaId: "M-MAE",
      cohorteId: "COH-MAE-2025",
      estado: "Activo",
      fechaIngreso: "10/02/2025",
      promedio: 88.0,
      uvsAprobadas: 18,
      totalUVs: 54,
      tituloTesis: "Estrategias de continuidad operativa ante disrupciones de cadena de suministro en retail",
      tutorTesis: "MSc. José Roberto Argueta",
      calificacionesRecientes: [
        { asignatura: "Dirección Estratégica Gerencial", codigo: "MAE-602", nota: 88, estado: "Aprobada" }
      ]
    },
    {
      id: "EST-07",
      cuentaUNAH: "20141011478",
      dni: "0801-1991-04419",
      nombres: "Miriam Judith",
      apellidos: "Bueso Cálix",
      correoInstitucional: "miriam.bueso@unah.edu.hn",
      telefono: "+504 9901-4477",
      universidadProcedencia: "UPNFM - Univ. Pedagógica Nacional Francisco Morazán",
      tituloValidadoUNAH: "Si",
      indicePregrado: 92.8,
      carreraPregrado: "Licenciatura en Educación Comercial",
      maestriaId: "M-MMIES",
      cohorteId: "COH-MMIES-2024",
      estado: "Egresado",
      fechaIngreso: "01/02/2024",
      promedio: 96.4,
      uvsAprobadas: 56,
      totalUVs: 56,
      tituloTesis: "Determinantes econométricos de la productividad laboral en pequeñas empresas manufactureras",
      tutorTesis: "Dr. Ramón Edgardo Cálix",
      calificacionesRecientes: [
        { asignatura: "Seminario de Tesis Econométrica", codigo: "MMIES-902", nota: 98, estado: "Aprobada" }
      ]
    },
    {
      id: "EST-08",
      cuentaUNAH: "20182006129",
      dni: "0601-1996-02381",
      nombres: "Denis Alexander",
      apellidos: "Gutiérrez Flores",
      correoInstitucional: "denis.gutierrez@unah.edu.hn",
      telefono: "+504 9720-3355",
      universidadProcedencia: "UNICAH - Universidad Católica de Honduras",
      tituloValidadoUNAH: "Si",
      indicePregrado: 85.0,
      carreraPregrado: "Licenciatura en Economía",
      maestriaId: "M-MCAF",
      cohorteId: "COH-MCAF-2025",
      estado: "Activo",
      fechaIngreso: "15/02/2025",
      promedio: 90.1,
      uvsAprobadas: 14,
      totalUVs: 54,
      tituloTesis: "Modelación estocástica del riesgo crediticio en carteras de crédito de consumo",
      tutorTesis: "Dr. Nelson Rolando Ávila",
      calificacionesRecientes: [
        { asignatura: "Teoría del Riesgo Financiero", codigo: "MCAF-601", nota: 90, estado: "Aprobada" }
      ]
    },
    {
      id: "EST-09",
      cuentaUNAH: "20131002931",
      dni: "0801-1990-11234",
      nombres: "Guillermo Antonio",
      apellidos: "Zelaya Valladares",
      correoInstitucional: "guillermo.zelaya@unah.edu.hn",
      telefono: "+504 9940-8812",
      universidadProcedencia: "Universidad Extranjera / Internacional",
      tituloValidadoUNAH: "Si",
      indicePregrado: 91.5,
      carreraPregrado: "Licenciatura en Finanzas (Universidad de San Carlos, Guatemala)",
      maestriaId: "M-MAE",
      cohorteId: "COH-MAE-2024",
      estado: "En Tesis",
      fechaIngreso: "15/02/2024",
      promedio: 94.0,
      uvsAprobadas: 48,
      totalUVs: 54,
      tituloTesis: "Estructura de capital óptima y valoración de empresas energéticas en Centroamérica",
      tutorTesis: "MSc. José Roberto Argueta",
      calificacionesRecientes: [
        { asignatura: "Finanzas Corporativas Avanzadas", codigo: "MAE-601", nota: 96, estado: "Aprobada" }
      ]
    },
    {
      id: "EST-10",
      cuentaUNAH: "20211009843",
      dni: "0501-1998-04711",
      nombres: "Sofía Alejandra",
      apellidos: "Paredes Umaña",
      correoInstitucional: "sofia.paredes@unah.edu.hn",
      telefono: "+504 9715-4433",
      universidadProcedencia: "USAP - Universidad de San Pedro Sula",
      tituloValidadoUNAH: "Si",
      indicePregrado: 87.0,
      carreraPregrado: "Licenciatura en Administración de Empresas Turísticas",
      maestriaId: "M-MDP",
      cohorteId: "COH-MDP-2024",
      estado: "Activo",
      fechaIngreso: "01/06/2024",
      promedio: 88.5,
      uvsAprobadas: 32,
      totalUVs: 52,
      tituloTesis: "Gestión de interesados y sostenibilidad en macroproyectos hoteleros",
      tutorTesis: "Ing. Carlos Alberto Vindel",
      calificacionesRecientes: [
        { asignatura: "Gestión Integral de Riesgos", codigo: "MDP-702", nota: 89, estado: "Aprobada" }
      ]
    }
  ],

  // Malla curricular oficial de asignaturas
  asignaturas: [
    { codigo: "MAE-601", nombre: "Finanzas Corporativas Avanzadas", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MAE", docente: "MSc. José Roberto Argueta", modalidad: "Híbrida" },
    { codigo: "MAE-602", nombre: "Dirección Estratégica Gerencial", uv: 4, ciclo: "Ciclo II", maestriaId: "M-MAE", docente: "MSc. José Roberto Argueta", modalidad: "Híbrida" },
    { codigo: "MAE-603", nombre: "Gestión de Portafolios de Inversión", uv: 4, ciclo: "Ciclo III", maestriaId: "M-MAE", docente: "Dr. Nelson Rolando Ávila", modalidad: "Presencial" },
    { codigo: "MDNI-901", nombre: "Comercio y Negociación Internacional", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MDNI", docente: "Dra. Brenda Lizeth Flores", modalidad: "Virtual" },
    { codigo: "MDNI-902", nombre: "Logística y Transporte Multimodal", uv: 4, ciclo: "Ciclo II", maestriaId: "M-MDNI", docente: "Dra. Brenda Lizeth Flores", modalidad: "Virtual" },
    { codigo: "MDP-701", nombre: "Gobernanza y Marco Ágil de Proyectos", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MDP", docente: "Ing. Carlos Alberto Vindel", modalidad: "Híbrida" },
    { codigo: "MDP-702", nombre: "Gestión Integral de Riesgos en Proyectos", uv: 4, ciclo: "Ciclo II", maestriaId: "M-MDP", docente: "Ing. Carlos Alberto Vindel", modalidad: "Híbrida" },
    { codigo: "MGI-801", nombre: "Gobierno de TI y Ciberseguridad Directiva", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MGI", docente: "MSc. Marcio Francisco Valle", modalidad: "Virtual" },
    { codigo: "MGI-802", nombre: "Arquitectura Empresarial y Cloud Computing", uv: 4, ciclo: "Ciclo II", maestriaId: "M-MGI", docente: "MSc. Marcio Francisco Valle", modalidad: "Virtual" },
    { codigo: "MME-601", nombre: "Neuromarketing y Conducta Digital del Consumidor", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MME", docente: "MSc. Silvia Patricia Moncada", modalidad: "Híbrida" },
    { codigo: "MMIES-901", nombre: "Métodos Cuantitativos y Econometría Aplicada", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MMIES", docente: "Dr. Ramón Edgardo Cálix", modalidad: "Presencial" },
    { codigo: "MCAF-601", nombre: "Teoría del Riesgo Financiero y Actuarial", uv: 4, ciclo: "Ciclo I", maestriaId: "M-MCAF", docente: "Dr. Nelson Rolando Ávila", modalidad: "Presencial" }
  ]
};

// Exportar globalmente para el frontend
if (typeof window !== 'undefined') {
  window.POSFASSE_DATA = POSFASSE_DATA;
}
